#!/bin/bash

start_directory="$(pwd)"
root_directory="$HOME/.emerson"

arduino_cli="$HOME/.emerson/bin/arduino-cli"
logfile="$HOME/.emerson/logs/$(date +%Y-%m-%d_%H-%M-%S).log"
[ ! -d "$HOME/.emerson/logs" ] && mkdir -p "$HOME/.emerson/logs"

usage() {
    echo "[!] usage: $0 <load <sketch_directory>|reload <sketch_directory>|stop>"
}

sketch_directory="$2"
set_sketch_directory() {
    [ -z "$sketch_directory" ] && echo "[!] missing sketch" && usage && exit 1
    [ ! -e "$sketch_directory" ] && sketch_directory="$HOME/Documents/Arduino/$sketch_directory"
    [ -f "$sketch_directory" ] && sketch_directory="$(dirname $sketch_directory)"
    [ ! -z "$sketch_directory" ] && sketch_directory=$(realpath "$sketch_directory")
    [ ! -e "$sketch_directory" ] && echo "[!] could not find sketch in $start_directory or $HOME/Documents/Arduino/" && usage && exit 1
}

start_franklin() {
    sketch_name=$(basename "$sketch_directory")
    sketch_location="$sketch_directory/build/arduino.avr.uno/$sketch_name.ino.with_bootloader.bin"
    echo "[+] starting server with $sketch_location"
    docker \
      run \
      --privileged \
      --env-file "$HOME/.emerson/.env" \
      --rm \
      --name ttt_emerson \
      -p 10314:10314 \
      -p 9001:9001 \
      --platform linux/amd64 \
      -v "$sketch_location:/opt/tuliptree/emerson/projects/arduino-uno-r3/flash.bin" \
      ghcr.io/tuliptreetech/emerson/lantern:latest >> $logfile 2>&1 &
}

compile() {
    echo "[+] compiling the sketch $sketch_directory"
    output=$("$arduino_cli" compile -b arduino:avr:uno -e -v "$sketch_directory")
    exit_code=$?
    if [ $exit_code -ne 0 ]; then
        echo "[!] compilation failed" 
        echo $output
        exit $exit_code
    fi
}

load_sketch() {
    echo "[+] loading sketch $sketch_directory"
    pushd "$root_directory" > /dev/null
    docker compose run --rm load
    popd > /dev/null
}

reload_sketch() {
    echo "[+] reloading sketch"
    pushd "$root_directory" > /dev/null
    docker compose run --rm reload
    popd > /dev/null
}

stop() {
    docker ps | grep ttt_emerson > /dev/null
    if [ $? -eq 0 ]; then
        echo "[+] stopping server"
        docker stop ttt_emerson
    fi
}

case "$1" in
    "load")
        set_sketch_directory
        compile
        stop
        start_franklin
        sleep 3
        load_sketch
        ;;
    "reload")
        set_sketch_directory
        compile
        reload_sketch
        ;;
    "stop")
        stop
        ;;
    *)
        usage
        exit 1
        ;;
esac
