#!/bin/bash

set -e

cd "$(dirname $0)" && root_directory="$(pwd)"

which docker > /dev/null 2>&1 || (
    echo "[!] docker is not installed." &&
    echo "please install either docker CE (https://docs.docker.com/engine/install/) or docker desktop (https://docs.docker.com/desktop/)" && 
    exit 1
)

echo "[+] installing necessary files for this user in ~/.emerson"
mkdir -p ~/.emerson/scripts

if [ ! -e "$HOME/.emerson/.env" ]; then
    echo -n "Enter your license key: "
    read license_key
    echo "license_key=$license_key" > "$HOME/.emerson/.env"
fi

cp "$root_directory/scripts/wait-for-it.sh" "$HOME/.emerson/scripts/wait-for-it.sh"
cp "$root_directory/scripts/load_sketch.py" "$HOME/.emerson/scripts/load_sketch.py"
cp "$root_directory/scripts/reload_sketch.py" "$HOME/.emerson/scripts/reload_sketch.py"

echo "[+] loading the docker images"
docker image load -i "$root_directory/emerson-lantern.tar"
docker image load -i "$root_directory/emerson-python.tar"

echo "[+] installing the arduino plugin"
rm -rf "${HOME}/.arduinoIDE/plugins/emerson"
mkdir -p "${HOME}/.arduinoIDE/plugins"
unzip -d "${HOME}/.arduinoIDE/plugins/" "$root_directory/emerson-arduino.zip"

echo "[+] emerson is successfully installed"

if [ "$1" == "cli" ]; then
    echo "[+] installing the arduino cli"

    arduino_cli="$HOME/.emerson/bin/arduino-cli"
    arduino_cli_directory="$HOME/.emerson"

    [ ! -d "$arduino_cli_directory" ] && mkdir -p "$arduino_cli_directory"
    if [ ! -e "$arduino_cli" ]; then
        pushd "$arduino_cli_directory" 
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 
        popd
    fi

    set +e
    $arduino_cli config init
    set -e

    $arduino_cli core update-index
    $arduino_cli core install arduino:avr

    cp "$root_directory/emerson-cli" "$HOME/.emerson/bin/emerson-cli"

    sudo cp "$root_directory/emerson-cli" /usr/local/bin/emerson-cli
    echo "[+] emerson-cli is successfully installed"
fi
